/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class cradle_rancune_tech_jni_JniTest */

#ifndef _Included_cradle_rancune_tech_jni_JniTest
#define _Included_cradle_rancune_tech_jni_JniTest
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     cradle_rancune_tech_jni_JniTest
 * Method:    plus
 * Signature: (II)I
 */
JNIEXPORT jint JNICALL Java_cradle_rancune_tech_jni_JniTest_plus
        (JNIEnv *, jclass, jint, jint);

/*
 * Class:     cradle_rancune_tech_jni_JniTest
 * Method:    minus
 * Signature: (II)I
 */
JNIEXPORT jint JNICALL Java_cradle_rancune_tech_jni_JniTest_minus
        (JNIEnv *, jclass, jint, jint);

JNIEXPORT void JNICALL
Java_cradle_rancune_tech_jni_JniTest_print(JNIEnv *env, jobject thiz, jstring string);

JNIEXPORT jstring JNICALL
Java_cradle_rancune_tech_jni_JniTest_getNativeString(JNIEnv *env, jclass clazz, jstring string);

#ifdef __cplusplus
}
#endif
#endif
