/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
#include <android/log.h>
/* Header for class cradle_rancune_tech_jni_JniTest */

#ifndef _Included_cradle_rancune_tech_jni_JniTest
#define _Included_cradle_rancune_tech_jni_JniTest
#ifdef __cplusplus
extern "C" {
#endif

JNIEXPORT void JNICALL
Java_cradle_rancune_tech_jni_JniTest_cacheFieldAndMethods(JNIEnv *env, jclass clazz);

JNIEXPORT jstring JNICALL
Java_cradle_rancune_tech_jni_JniTest_getNativeString(JNIEnv *env, jclass clazz, jstring string);

JNIEXPORT jint JNICALL
Java_cradle_rancune_tech_jni_JniTest_intArraySum(JNIEnv *env, jclass clazz,
                                                 jintArray intArray_, jint num_);

JNIEXPORT jintArray JNICALL
Java_cradle_rancune_tech_jni_JniTest_getIntArray(JNIEnv *env, jclass clazz, jint num_);

JNIEXPORT jobjectArray JNICALL
Java_cradle_rancune_tech_jni_JniTest_getTwoDimensionalArray(JNIEnv *env, jclass clazz,
                                                            jint row, jint column);

JNIEXPORT void JNICALL
Java_cradle_rancune_tech_jni_JniTest_printAnimalsName(JNIEnv *env, jclass clazz,
                                                      jobjectArray beans);

JNIEXPORT void JNICALL
Java_cradle_rancune_tech_jni_JniTest_accessInstanceAndStaticField(JNIEnv *env, jobject thiz,
                                                                  jobject animal);

JNIEXPORT void JNICALL
Java_cradle_rancune_tech_jni_JniTest_callInstanceAndStaticMethod(JNIEnv *env, jobject thiz,
                                                                 jobject animal);

JNIEXPORT jobject JNICALL
Java_cradle_rancune_tech_jni_JniTest_invokeAnimalConstructor(JNIEnv *env, jobject thiz,
                                                             jstring name);

JNIEXPORT jobject JNICALL
Java_cradle_rancune_tech_jni_JniTest_allocAnimalConstructor(JNIEnv *env, jobject thiz,
                                                            jstring name);

JNIEXPORT void JNICALL
Java_cradle_rancune_tech_jni_JniTest_callSuperMethod(JNIEnv *env, jobject thiz, jstring name);

JNIEXPORT jobject JNICALL
Java_cradle_rancune_tech_jni_JniTest_useCacheMethod(JNIEnv *env, jobject thiz, jstring name);

#ifdef __cplusplus
}
#endif
#endif