/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class cradle_rancune_media_ffmpeg_FFmpeg2 */

#ifndef _Included_cradle_rancune_media_ffmpeg_FFmpeg2
#define _Included_cradle_rancune_media_ffmpeg_FFmpeg2
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     cradle_rancune_media_ffmpeg_FFmpeg2
 * Method:    getCoder
 * Signature: ()Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_cradle_rancune_media_ffmpeg_FFmpeg2_getCoder
        (JNIEnv *, jobject);

#ifdef __cplusplus
}
#endif
#endif
